name = "TelegramProgressBot"
uuid = "057b5087-46ea-4fac-8e94-547ec48c6895"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com>", "Petru-Vlad Toma <tomapv@gmail.com>"]
version = "0.1.0"

[deps]
ConfigEnv = "01234589-554d-41b7-ae5c-7b6ee2db6796"
Telegram = "1da6f4ae-116c-4c38-8ee9-19974ff3601d"

[compat]
Telegram = "1.1"
ConfigEnv = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
